import type { Language } from '@/lib/i18n';
import type { LegalDocument } from './config';

export const legalCopy = {
  tr: {
    titles: { privacy: 'KVKK Aydınlatma Metni', storage: 'Çerez ve Tarayıcı Depolama Politikası', terms: 'Kullanım Koşulları', requests: 'Kişisel Veri Başvuruları ve İletişim' },
    home: 'Planlayıcıya dön', version: 'Sürüm', effective: 'Yürürlük tarihi', draft: 'Henüz yürürlükte değil',
    incomplete: 'Yayın öncesi taslak: veri sorumlusunun kimliği, iletişim bilgileri ve hizmet sağlayıcı bilgileri henüz tamamlanmadı. Bu metin yayıma hazır değildir.',
    controller: 'Veri sorumlusu', address: 'Posta adresi', email: 'Başvuru e-postası', missing: 'Henüz doğrulanmadı',
    settings: 'Tarayıcı verileri ve gizlilik', privacy: 'KVKK', terms: 'Koşullar', storage: 'Depolama', requests: 'Veri başvuruları',
    noticeLink: 'KVKK Aydınlatma Metni', storageLink: 'Depolama politikası',
    notices: {
      account: 'E-posta adresiniz ve parolanız hesap oluşturma, doğrulama ve güvenli giriş için sunucu üzerinden Supabase Auth’a iletilir. Parola sağlayıcı tarafından korunur. Bu bilgilendirme bir açık rıza talebi değildir.',
      profile: 'Ad, soyad, isteğe bağlı doğum tarihi ve takma ad ile seçtiğiniz ana dal, ÇAP ve yandal bilgileri hesabınızın Supabase profilinde saklanır. Profilinizi burada düzeltebilir, verilerinizi gizlilik bölümünden indirebilirsiniz.',
      transcript: 'Yalnızca ders, dönem, kredi ve not satırlarını yapıştırın; öğrenci numarası, kimlik veya sağlık bilgisi eklemeyin. Ayrıştırılan dersler, ilerleme ve hesaplamalar bu tarayıcıda saklanır; transkript sunucuya yüklenmez. Aynı tarayıcıyı kullanan başka hesaplar bu yerel verileri görebilir. Çıkış yapmak bunları silmez.',
      planner: 'Planlar ve akademik ilerleme bu tarayıcıda saklanır ve çıkıştan sonra kalır. Ortak cihaz kullanıyorsanız gizlilik bölümünden tarayıcı verilerini temizleyin.',
    },
    controls: {
      title: 'Verileriniz', local: 'Bu tarayıcıdaki veriler',
      localHelp: 'Planlar, dersler, notlar, tercihler ve ilerleme hesaplar arasında paylaşılır. İndirme yalnızca bu tarayıcıyı kapsar; dosyayı güvenli saklayın. Temizleme diğer cihazlara veya Supabase hesabınıza uygulanmaz.',
      exportLocal: 'Tarayıcı verilerini indir', clear: 'Tarayıcı verilerini temizle', clearConfirm: 'Bu tarayıcıdaki tüm Simplify planları, transkript, ilerleme, dil ve tema tercihleri silinsin mi? İşlem geri alınamaz.',
      account: 'Hesap verileri', accountHelp: 'Kayıtlı profilinizi Profil sayfasından görüntüleyip düzeltebilirsiniz. Hesap indirmesi e-posta, hesap kimliği, tarihleri ve profilinizi kapsar; sunucu günlüklerini veya yedekleri kapsamaz. Bu kolaylık, KVKK kapsamında genel bir veri taşınabilirliği hakkı vaadi değildir.',
      exportAccount: 'Hesap verilerini indir', delete: 'Hesabımı sil', password: 'Mevcut parola',
      deletionHelp: 'Silme, Supabase’teki hesabınızı ve profilinizi kaldırır. Başarılı olursa bu tarayıcıdaki planlar da temizlenir. Diğer tarayıcılardaki verileri ayrıca temizleyin. Sağlayıcı günlükleri, yedekler ve hukuken saklanması gereken kayıtlar bu işlemle anında silinmez.',
      confirmation: 'Hesabımın ve profilimin kalıcı olarak silinmesini istiyorum.',
      unavailable: 'Otomatik hesap silme henüz yapılandırılmadı. Başvuru kanalı için Kişisel Veri Başvuruları sayfasını kullanın.',
      busy: 'İşleniyor…', success: 'İndirme hazırlandı.', cleared: 'Tarayıcı verileri temizlendi.',
      error: 'İşlem tamamlanamadı. Tekrar deneyin veya veri başvuru kanalını kullanın.',
      unauthorized: 'Oturumunuz geçersiz veya e-posta doğrulanmamış. Yeniden giriş yapın.',
      invalid: 'Mevcut parolanızı girin ve silme talebinizi onaylayın.', verification: 'Mevcut parola doğrulanamadı. Hesap silinmedi.',
      deletionSuccess: 'Hesap silindi.', localFailed: 'Hesap silindi; tarayıcı depolamasına erişilemedi. Tarayıcı ayarlarından bu sitenin verilerini temizleyin.',
    },
    contact: {
      unavailable: 'Başvuru kanalı henüz yapılandırılmadı; burada başvuru gönderilemez. İşletmeci yayın öncesinde çalışan e-posta ve posta adresini eklemelidir.',
      emailButton: 'E-posta uygulamasını aç', emailHelp: 'Bu bağlantı e-posta uygulamanızı açar; mesajı sizin göndermeniz gerekir. Daha önce bildirdiğiniz, hesapta kayıtlı e-posta adresinizi kullanın. Parola, oturum belirteci veya transkript göndermeyin.',
    },
    storageHeaders: ['Teknoloji / tanımlayıcı', 'Sağlayıcı ve kategori', 'Amaç', 'Ömür'],
    noExpiry: 'Otomatik süre sonu yok; siz silene veya tarayıcı temizleyene kadar.',
    firstParty: 'Simplify / istenen işlev', authProvider: 'Simplify alan adı / Supabase Auth / gerekli kimlik doğrulama',
    storedPurposes: ['Adlandırılmış haftalık planlar ve seçilen dersler', 'Ders, gün, saat ve CRN tercihleri ile üretilen program', 'Ayrıştırılmış transkript: dersler, notlar, kredi ve dönemler', 'Her plan için manuel ve transkript kaynaklı ilerleme', 'Son seçilen program ve müfredat', 'Seçtiğiniz dili hatırlama', 'Seçtiğiniz temayı hatırlama'],
  },
  en: {
    titles: { privacy: 'KVKK Privacy Notice', storage: 'Cookie and Browser Storage Policy', terms: 'Terms of Use', requests: 'Privacy Requests and Contact' },
    home: 'Back to planner', version: 'Version', effective: 'Effective date', draft: 'Not yet effective',
    incomplete: 'Pre-launch draft: controller identity, contact details and provider information are incomplete. This notice is not ready for publication.',
    controller: 'Data controller', address: 'Postal address', email: 'Request email', missing: 'Not yet verified',
    settings: 'Browser data and privacy', privacy: 'Privacy', terms: 'Terms', storage: 'Storage', requests: 'Privacy requests',
    noticeLink: 'KVKK Privacy Notice', storageLink: 'Storage policy',
    notices: {
      account: 'Your email and password are sent through the server to Supabase Auth for account creation, verification and secure sign-in. The provider protects your password. This information is not a request for explicit consent.',
      profile: 'Your name, surname, optional birthdate and nickname, and selected main major, double majors and minors are saved in your Supabase account profile. You can correct your profile here and download your data in the privacy section.',
      transcript: 'Paste only course, term, credit and grade rows; omit student numbers, identity and health information. Parsed courses, progress and calculations are stored in this browser; the transcript is not uploaded to the server. Other accounts using this browser can see this local data. Signing out does not delete it.',
      planner: 'Plans and academic progress are stored in this browser and remain after sign-out. On a shared device, clear browser data from the privacy section.',
    },
    controls: {
      title: 'Your data', local: 'Data in this browser',
      localHelp: 'Plans, courses, grades, preferences and progress are shared between accounts. Downloads cover only this browser; keep the file secure. Clearing does not affect other devices or your Supabase account.',
      exportLocal: 'Download browser data', clear: 'Clear browser data', clearConfirm: 'Delete all Simplify plans, transcript, progress, language and theme preferences in this browser? This cannot be undone.',
      account: 'Account data', accountHelp: 'View and correct your saved profile on the Profile page. The account download includes email, account ID, dates and profile; it excludes server logs and backups. This convenience does not promise a general right to data portability under KVKK.',
      exportAccount: 'Download account data', delete: 'Delete my account', password: 'Current password',
      deletionHelp: 'Deletion removes your Supabase account and profile. On success, plans in this browser are also cleared. Clear data in other browsers separately. Provider logs, backups and records lawfully required to be retained are not immediately erased by this operation.',
      confirmation: 'I request permanent deletion of my account and profile.',
      unavailable: 'Automatic account deletion is not configured yet. Use the Privacy Requests page for request channel information.',
      busy: 'Processing…', success: 'Download prepared.', cleared: 'Browser data cleared.',
      error: 'The operation could not be completed. Try again or use the privacy request channel.',
      unauthorized: 'Your session is invalid or your email is unverified. Sign in again.',
      invalid: 'Enter your current password and confirm the deletion request.', verification: 'Your current password could not be verified. The account was not deleted.',
      deletionSuccess: 'Account deleted.', localFailed: 'Account deleted; browser storage could not be accessed. Clear this site’s data in browser settings.',
    },
    contact: {
      unavailable: 'The request channel is not configured; you cannot submit a request here. The operator must add working email and postal addresses before launch.',
      emailButton: 'Open email application', emailHelp: 'This link opens your email application; you must send the message yourself. Use the email you previously provided that is registered to your account. Do not send passwords, session tokens or transcripts.',
    },
    storageHeaders: ['Technology / identifier', 'Provider and category', 'Purpose', 'Lifetime'],
    noExpiry: 'No automatic expiry; until you delete it or the browser clears it.',
    firstParty: 'Simplify / requested functionality', authProvider: 'Simplify domain / Supabase Auth / necessary authentication',
    storedPurposes: ['Named weekly plans and selected courses', 'Course, day, time and CRN preferences and generated schedule', 'Parsed transcript: courses, grades, credits and terms', 'Manual and transcript-derived progress for each plan', 'Last selected program and curriculum', 'Remember your selected language', 'Remember your selected theme'],
  },
} as const;

type Section = { title: string; paragraphs: string[] };
export function legalSections(document: LegalDocument, language: Language): Section[] {
  const tr = language === 'tr';
  switch (document) {
    case 'privacy': return tr ? [
      { title: 'Kapsam ve toplama yöntemleri', paragraphs: ['Simplify, İTÜ öğrencileri için bağımsız bir akademik planlama aracıdır. Bilgiler hesap ve profil formlarından, tarayıcıda yapıştırılan transkript satırlarından ve siteye yapılan teknik isteklerden elde edilir. Üniversite hesabı parolası, kimlik belgesi veya dosya yüklemesi istenmez. Notlardan GPA, mezuniyet ilerlemesi ve ders uygunluğu hesaplanır. Bu hesaplamalar resmi üniversite kararı değildir.'] },
      { title: 'Amaçlar ve hukuki sebepler', paragraphs: ['E-posta, hesap kimliği, doğrulama tarihleri ve kimlik doğrulama bilgileri hesap açma, güvenli giriş, doğrulama ve parola kurtarma için; ad, soyad, isteğe bağlı doğum tarihi ve takma ad ile ana dal, ÇAP ve yandal seçimleri profil ve planlama hizmetini sağlamak için işlenir. Hizmetin kurulması ve ifasıyla doğrudan ilgili ve gerekli işlemler için KVKK m.5/2(c) esas alınır. İsteğe bağlı kişisel alanların gerekliliği ve hukuki sebebi işletmeci tarafından yayın öncesi ayrıca değerlendirilecektir; bu alanları boş bırakabilirsiniz.', 'Tarayıcıdaki ders, not, dönem ve kredi kayıtları ile tercih ve program verileri, talep ettiğiniz akademik hesaplama ve kayıtlı plan işlevleri için kullanılır (m.5/2(c)). IP adresi, istek zamanı, URL ve teknik hata kayıtları barındırma veya kimlik doğrulama sağlayıcısına ulaşabilir; ölçülü güvenlik ve kötüye kullanım önleme kayıtları için m.5/2(f) kapsamında haklarınızla dengelenmiş meşru menfaat değerlendirmesi gerekir. Gerçek günlük kapsamı yayın öncesi doğrulanmalıdır.', 'Başvuru kimliği, iletişim bilgileri ve talep içeriği KVKK başvurularının yanıtlanması yükümlülüğü için m.5/2(ç); gerekli uyuşmazlık kayıtları bir hakkın tesisi, kullanılması veya korunması için m.5/2(e) kapsamında işlenir. Özel nitelikli veri istenmez. Aydınlatma, açık rıza değildir; tüm işlemler için toplu rıza istenmez.'] },
      { title: 'Alıcılar ve aktarım', paragraphs: ['Hesap ve profil bilgileri sunucu üzerinden Supabase Auth’a gider. Doğrulama ve kurtarma e-postaları yapılandırılmış e-posta sağlayıcısıyla gönderilir. Barındırma sağlayıcısı site isteklerini işler; yetkili işletmeci personeli hizmet ve veri başvuruları için gereken kayıtlara erişebilir. Yetkili kamu makamlarına yalnızca uygulanabilir bir hukuki yükümlülük kapsamında bilgi verilebilir.', 'Transkript metni ve yerel planlar sunucuya gönderilmez. Ders ve müfredat aramaları program/plan/ders tanımlayıcılarıyla Simplify sunucusuna, oradan kamuya açık İTÜ OBS uçlarına gider; transkript ve hesap bilgisi OBS’ye iletilmez. Sunucu tarafındaki plan seçimleri ve istek günlükleri akademik ilgi çıkarımına imkân verebilir. İTÜ, bu hizmetin kimlik doğrulama sağlayıcısı değildir.'] },
      { title: 'Saklama ve güvenlik', paragraphs: ['Yerel planlar ve transkriptler otomatik sona ermez; siz veya tarayıcı silene kadar kalır. Çıkış bunları silmez. Ortak tarayıcıdaki başka hesaplar bu verilere erişebilir. Profilinizi düzeltebilir, yerel verileri indirebilir ve temizleyebilirsiniz.', 'Hesap silme, sunucudaki hesabı ve profilini kaldırmayı hedefler; sağlayıcı günlükleri ve yedekler için ayrı süreler ve süreçler gerekir. Yedeklerden anında silme vaadi verilmez. Yasal saklama gerekçesi bulunan kayıtlar sınırlandırılmış erişimle korunmalıdır. Henüz doğrulanmamış saklama süreleri aşağıda gösterilir.'] },
      { title: 'Haklarınız', paragraphs: ['KVKK m.11 kapsamında işleme olup olmadığını öğrenebilir, bilgi isteyebilir, amaç ve amaca uygun kullanımı öğrenebilir, yurt içi/yurt dışı alıcıları öğrenebilir, eksik veya yanlış bilgileri düzelttirebilir, m.7 şartlarında silme/yok etme isteyebilir ve düzeltme/silme işlemlerinin alıcılara bildirilmesini talep edebilirsiniz. Münhasıran otomatik analizle aleyhinize doğan sonuçlara itiraz edebilir ve hukuka aykırı işlemeyle uğradığınız zararın giderilmesini isteyebilirsiniz. Başvuru yöntemleri Kişisel Veri Başvuruları sayfasındadır.'] },
    ] : [
      { title: 'Scope and collection methods', paragraphs: ['Simplify is an independent academic planning tool for İTÜ students. Information comes from account and profile forms, transcript rows pasted in the browser, and technical site requests. University passwords, identity documents and file uploads are not requested. GPA, graduation progress and course eligibility are inferred from grades. These calculations are not official university decisions.'] },
      { title: 'Purposes and legal grounds', paragraphs: ['Email, account ID, verification dates and authentication information support account creation, secure sign-in, verification and password recovery. Name, surname, optional birthdate and nickname, and main major, double-major and minor choices support profiles and planning. Processing directly related and necessary to establishing or performing the service relies on KVKK Article 5(2)(c). The operator must separately assess the necessity and ground for optional personal fields before launch; you may leave them blank.', 'Browser course, grade, term and credit records, preferences and schedules support your requested academic calculations and saved plans (Article 5(2)(c)). IP address, request time, URL and technical errors may reach hosting or authentication providers. Proportionate security and abuse-prevention logs require a legitimate-interest assessment balanced against your rights under Article 5(2)(f). Actual log contents must be confirmed before launch.', 'Request identity, contact details and request contents support the legal obligation to answer KVKK requests under Article 5(2)(ç). Necessary dispute records rely on establishing, exercising or protecting a right under Article 5(2)(e). Special-category data is not requested. A privacy notice is not explicit consent; no blanket processing consent is requested.'] },
      { title: 'Recipients and transfers', paragraphs: ['Account and profile details go through the server to Supabase Auth. Verification and recovery emails are sent through the configured email provider. The hosting provider handles site requests. Authorized operator personnel may access records needed for service and privacy requests. Disclosure to competent public authorities requires an applicable legal obligation.', 'Transcript text and local plans are not sent to the server. Course and curriculum searches send program/plan/course identifiers to Simplify’s server and then to public İTÜ OBS endpoints; transcripts and account information are not sent to OBS. Server-side plan selections and request logs may reveal academic interests. İTÜ is not this service’s authentication provider.'] },
      { title: 'Retention and security', paragraphs: ['Local plans and transcripts do not automatically expire; they remain until you or the browser deletes them. Signing out does not clear them. Other accounts in a shared browser can access this data. You can correct your profile, download local data and clear it.', 'Account deletion aims to remove the server account and its profile. Provider logs and backups require separate periods and procedures. Immediate erasure from backups is not promised. Records with lawful retention grounds must have restricted access. Unconfirmed retention periods are shown below.'] },
      { title: 'Your rights', paragraphs: ['Under KVKK Article 11 you may learn whether processing occurs, request information, learn its purpose and whether use matches that purpose, learn domestic/overseas recipients, correct incomplete or inaccurate data, seek deletion/destruction under Article 7, and ask that recipients be notified of correction/deletion. You may object to adverse results arising solely from automated analysis and seek compensation for damage caused by unlawful processing. See Privacy Requests for submission methods.'] },
    ];
    case 'storage': return tr ? [
      { title: 'Depolama ve seçimler', paragraphs: ['Bu sürümde analiz, reklam, izleme pikseli, gömülü üçüncü taraf içerik veya pazarlama SDK’sı yoktur. sessionStorage ve IndexedDB kullanımı bulunmadı. Bu nedenle isteğe bağlı izleme için rıza penceresi gösterilmez. Yeni isteğe bağlı bir amaç eklenmeden önce ayrı değerlendirme ve gerekiyorsa önceden açık rıza mekanizması gerekir.', 'Kimlik doğrulama çerezleri giriş hizmeti için gereklidir. Plan depolaması kaydetme ve sonraki kullanımda geri getirme işlevine hizmet eder. Dil ve tema yalnızca seçtiğiniz tercihi hatırlar; sistem temasını algılamak tek başına kayıt yazmaz. Bunlar izleme amaçlı kullanılmaz. Her amaç ayrı değerlendirilmiştir; işlevsellik etiketi tek başına rıza muafiyeti sağlamaz.', 'localStorage kayıtları yalnızca bu alan adındaki tarayıcıda kalır. HTTP çerezleri isteklerle sunucuya gider; Supabase sunucu istemcisi kimlik doğrulama için ilgili oturumu kullanır. Sağlayıcı veya CDN’in dağıtımda ekleyebileceği kayıtlar henüz doğrulanmadı; yayından önce gerçek ağ ve depolama kontrolü yapılmalıdır.'] },
    ] : [
      { title: 'Storage and choices', paragraphs: ['This version has no analytics, ads, tracking pixels, embedded third-party content or marketing SDKs. No sessionStorage or IndexedDB use was found. Consequently no optional-tracking consent popup is shown. New optional purposes require separate assessment and, where necessary, prior explicit-consent controls before activation.', 'Authentication cookies are necessary for sign-in. Planner storage supports saving and restoring your work. Language and theme remember only your selected preference; detecting the system theme alone does not write storage. None is used for tracking. Each purpose was assessed individually; a functionality label alone does not exempt storage from consent.', 'localStorage records stay in this browser for this origin. HTTP cookies travel to the server with requests; the Supabase server client uses the relevant session for authentication. Storage introduced by the deployed provider or CDN is unverified; inspect actual network and storage behavior before launch.'] },
    ];
    case 'terms': return tr ? [
      { title: 'Bağımsız akademik araç', paragraphs: ['Simplify, ana dal, ÇAP ve yandal için profil, mezuniyet/GPA tahmini, dönem önerisi ve program üretimi sağlar. Doğrulanmış resmi İTÜ ilişkisi yoktur. İTÜ adı hedef üniversiteyi belirtir; onay, temsil veya ortaklık anlamına gelmez.', 'Öneriler mevcut ders, müfredat, denklik ve sizin girdiğiniz kayıtlara bağlıdır. Eksik, eski veya yanlış veriler sonucu etkiler. Kayıt, ön koşul, eş koşul, kontenjan, denklik ve mezuniyet kararlarını OBS, öğrenci işleri ve yetkili akademik birimlerle doğrulayın. Simplify ders kaydı yapmaz ve mezuniyet kararı vermez.'] },
      { title: 'Kaynaklar ve sınırlar', paragraphs: ['Kamuya açık İTÜ OBS verileri kullanılır. Ders programları sunucuda en erken 5 dakikada bir, müfredat ayrıntıları 6 saatlik önbellekle yenilenir; bu süreler üniversitenin değişikliği hemen yansıtacağı garantisi değildir. Program seçici ve denklik kayıtları ayrıca alınmış anlık görüntülerdir; tarihleri aşağıdadır.', 'Tanınan Türkçe/İngilizce ders eşleştirmeleri uygulama politikası olarak değerlendirilir; her biri bağımsız resmi denklik kararı değildir. Arama sınırları program karşılaştırmasını eksik bırakabilir. Bilinmeyen kayıt koşulları ve uygunluk uyarıları resmi doğrulama gerektirir.'] },
      { title: 'Hesap ve kullanım', paragraphs: ['Hesabınızı ve cihazınızı koruyun; başkasının kişisel kaydını izinsiz girmeyin. Güvenlik kontrollerini aşmayın veya hizmeti kötüye kullanmayın. Bu sürümde ödeme ve pazarlama gönderimi yoktur. Yeni ücretli hizmetler ayrı koşul ve bilgilendirme gerektirir.', 'Hatalı veri veya hizmet kesintisi olabilir. Bu açıklamalar emredici hukuk kapsamındaki haklarınızı ve işletmecinin yasal sorumluluğunu kaldırmaz. Değişiklikler sürüm ve yürürlük tarihiyle yayımlanır; yeni veri amaçları ayrıca bildirilir. Sorunlar ve veri başvuruları için iletişim sayfasını kullanın.'] },
    ] : [
      { title: 'Independent academic tool', paragraphs: ['Simplify provides profiles, graduation/GPA estimates, semester recommendations and schedule generation for main majors, double majors and minors. No official İTÜ relationship has been verified. The university’s name identifies the intended university and does not imply endorsement, representation or partnership.', 'Recommendations depend on available course, curriculum and equivalence data and your records. Missing, stale or incorrect data affects results. Verify registration, prerequisites, corequisites, quotas, equivalences and graduation decisions with OBS, student affairs and authorized academic units. Simplify does not register courses or decide graduation.'] },
      { title: 'Sources and limitations', paragraphs: ['Public İTÜ OBS data is used. Course schedules are revalidated on the server no more frequently than every 5 minutes; curriculum detail has a 6-hour cache. These periods do not guarantee immediate reflection of university changes. Program selectors and equivalence records are separately captured snapshots; dates appear below.', 'Recognized Turkish/English course counterparts are application policy; each is not a separate official equivalence decision. Search limits may leave schedule comparison incomplete. Unknown registration rules and eligibility warnings require official verification.'] },
      { title: 'Account and use', paragraphs: ['Protect your account and device; do not enter another person’s records without permission. Do not bypass security controls or abuse the service. This version has no payments or promotional messages. New paid services require separate terms and information.', 'Data errors and service interruptions may occur. These explanations do not remove mandatory legal rights or the operator’s statutory responsibilities. Changes are published with version and effective date; new processing purposes receive separate notice. Use the contact page for issues and privacy requests.'] },
    ];
    case 'requests': return tr ? [
      { title: 'Başvuru ve kimlik doğrulama', paragraphs: ['Başvurunuzu veri sorumlusuna yazılı olarak, KEP/güvenli elektronik imza/mobil imza ile veya daha önce bildirdiğiniz ve sistemde kayıtlı e-posta adresinizden iletebilirsiniz. Yapılandırılmış iletişim bilgileri aşağıdadır. Bu sayfa mesaj ileten bir form değildir.', 'Başvuruda ad, soyad; yazılı başvuruda imza; Türkiye Cumhuriyeti vatandaşları için T.C. kimlik numarası, yabancılar için uyruk, pasaport veya varsa kimlik numarası; tebligata esas yerleşim yeri/iş yeri adresi; varsa bildirim e-postası, telefon/faks ve talep konusu yer almalıdır. Konuya ilişkin gerekli bilgi ve belgeler eklenebilir. Kimlik belgesi kopyasını veya transkriptinizi gereksiz yere eklemeyin. İşletmeci başvuruyla orantılı kimlik doğrulaması yapmalı; doğrulama tamamlanmadan kişisel veri açıklamamalıdır.'] },
      { title: 'Süreler ve itiraz', paragraphs: ['Başvurular niteliğine göre en kısa sürede ve en geç 30 gün içinde yanıtlanmalıdır. Yanıt yazılı veya elektronik ortamda, gerekçesi ve bildirim tarihi ispatlanabilir şekilde verilir. İşlem kural olarak ücretsizdir; ek maliyetler için Kurulun tarifesi uygulanabilir.', 'Ret, yetersiz yanıt veya süresinde yanıt verilmemesi hâlinde cevabı öğrenmeden itibaren 30 gün ve her hâlde başvurudan itibaren 60 gün içinde KVKK Kuruluna şikâyet hakkınız vardır. Önce veri sorumlusuna başvuru yolu tüketilmelidir.'] },
      { title: 'Hesap ve yerel kayıtlar', paragraphs: ['Giriş yaptıktan sonra Profil sayfasındaki gizlilik bölümünden profil ve hesap verilerini indirebilir, mevcut parola doğrulamasıyla hesabınızı silebilirsiniz (silme hizmeti yapılandırılmışsa). Profil alanlarını aynı sayfada düzeltebilirsiniz. Çerez/depolama sayfasındaki temizleme yalnızca mevcut tarayıcıyı kapsar.', 'Silme talepleri yasal saklama istisnaları ve alıcılara bildirim gerekliliğiyle birlikte değerlendirilir. Yedekler ayrı süreçle ele alınır; bu araç anında yedek silme sözü vermez. Tarayıcı indirmesi tüm sunucu kayıtlarına erişim başvurusunun yerine geçmez.'] },
    ] : [
      { title: 'Requests and identity verification', paragraphs: ['Submit to the controller in writing, via registered electronic mail (KEP), secure electronic signature or mobile signature, or from the email previously provided and registered in the system. Configured contacts appear below. This page is not a message-delivery form.', 'A request must include name and surname; signature for written submissions; Turkish identity number for Turkish citizens or nationality and passport/identity number for foreign nationals; residence/business address for notification; notification email, telephone/fax if available; and the request subject. Attach only relevant information and documents. Do not unnecessarily attach identity-document copies or transcripts. The operator must use proportionate identity verification and must not disclose personal data before verification.'] },
      { title: 'Deadlines and complaints', paragraphs: ['Requests must be answered as soon as their nature permits and within 30 days at the latest. Written or electronic replies must make reasons and the notification date demonstrable. Handling is generally free; additional costs may be charged only under the Board’s tariff.', 'For rejection, an inadequate response or no timely response, you may complain to the KVKK Board within 30 days of learning the response and in all cases within 60 days of applying to the controller. You must first apply to the controller.'] },
      { title: 'Account and local records', paragraphs: ['After signing in, use the Profile privacy section to download profile and account data, or delete the account with current-password verification when deletion is configured. Correct profile fields on the same page. Clearing on the storage page covers only this browser.', 'Deletion requests must account for lawful retention exceptions and notification to recipients. Backups require separate handling; the tool does not promise immediate backup erasure. Browser downloads do not replace requests for access to all server-held records.'] },
    ];
  }
}
